language: python

env:
  - export TEST_DATABASE_URL='postgresql://postgres:star2030@localhost/test_politico'
  - FLASK_ENV=testing

python:
  - 3.6.7

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install pytest

services:
  - postgresql

before_script:
  - psql -c 'create database politico;' -U postgres
  - psql -c 'create database test_politico;' -U postgres

script:
  - pytest --cov=app

after_success:
  - coveralls
