language: python

env:
  global:
    - export TEST_DATABASE_URL='postgresql://postgres:star2030@localhost/test_politico'
    - export FLASK_ENV=testing
    - export JWT_SECRET_KEY
    - export ADMIN=('Godfrey', 'Wanjala', 'Willies', %s, %s, '0721175171', 'http://@wanjala', True)
    - export ADMIN_EMAIL='gwiliez@ymail.com'
    - export ADMIN_PASS='admin'

python:
  - 3.6.7

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install pytest

services:
  - postgresql

before_script:
  - psql -c 'create database politico;' -U postgres
  - psql -c 'create database test_politico;' -U postgres

script:
  - pytest --cov=app

after_success:
  - coveralls
